### PR TITLE
feat: use reclient on init instead of goma

### PR DESCRIPTION
**Pull request by MarshallOfSound**
As in title, init should use reclient now

### CODE REVIEW

**Comment by dsanders11** [comment]
CI is hanging on this, but can't tell if it's legitimate or something flaky, CI on other PRs are being quite slow at the moment as well.

**Comment by ckerr** [comment]
Might not just be CI? `yarn test` is hanging for me in `e-show-spec.js`.

The code changes in this PR look fine, so my guess (w/o having looked at the test) is that the test just needs to be updated

**Comment by MarshallOfSound** [comment]
Could be hanging on a reclient auth request?

**Comment by dsanders11** [comment]
Was indeed hanging on the reclient auth request, so I pushed a commit to skip it during tests.

**Review by dsanders11 — APPROVED** [review]

**Review by jkleinsc — APPROVED** [review]

**Pull request merged**
